version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: my_task_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: task_management
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  app:
    build: .
    container_name: my_task_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/task_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration/schema,classpath:db/migration/data
      SPRING_FLYWAY_ENABLED: "true"
    ports:
      - "8080:8080"