
CREATE TABLE user_accounts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  user_name VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE (public_id),
  UNIQUE (email)
);

CREATE TABLE projects (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  public_id CHAR(36) NOT NULL,
  project_caption VARCHAR(100) NOT NULL,
  description TEXT,
  status ENUM('ACTIVE','ARCHIVED') DEFAULT 'ACTIVE',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user_accounts (id),
  UNIQUE (public_id)
);
